dependencies:
- name: zeebe-broker
  version: 0.1.0
  repository: file://./charts/zeebe
- name: zeebe-loadtest-starter
  version: 0.1.0
  repository: file://./charts/starter
- name: zeebe-loadtest-worker
  version: 0.1.0
  repository: file://./charts/worker

