apiVersion: v1
kind: Service
metadata:
  name: elastic-lb
  labels:
    app: elastic
spec:
  type: LoadBalancer
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service: elasticsearch
