apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
    - port: 5601
      targetPort: ui
      protocol: TCP
      name: http
  selector:
    app: kibana
