apiVersion: v1
kind: Service
metadata:
  name: operate
  labels:
    app: operate
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: operate-http
      protocol: TCP
      name: http
  selector:
    app: operate
